## 异常&错误处理

本文主要介绍在Swift学习中，如何对可能抛出的异常进行处理，了解为什么要throws，什么情况下需要自己写throw, 如果捕获throw的异常

### OC中如何处理可能抛出的异常

在oc中我们最经常用到的就是

```objc
- (BOOL)writeToFile:(NSString *)path options:(NSDataWritingOptions)writeOptionsMask error:(NSError **)errorPtr;

```
这个方法我们在使用时 需要新建一个NSError对象error, 并将这个对象作为上面方法调用的最后一个参数进行传入，如果这个方法调用出现了异常，那么error就会被赋值，我们可以通过这种方式来判断，这个方法是否执行成功，若未成功错误是什么。

但是通常我们都会偷懒，传一个null最为参数

### Swift中可能抛出异常

相同的方法，我们看下在Swift中的定义

```swift 
    /// Write the contents of the `Data` to a location.
    ///
    /// - parameter url: The location to write the data into.
    /// - parameter options: Options for writing the data. Default value is `[]`.
    /// - throws: An error in the Cocoa domain, if there is an error writing to the `URL`.
    public func write(to url: URL, options: Data.WritingOptions = []) throws
```

我们发现方法的修饰词职工多了一个throws, 而在调用这类使用throws修饰的方法时如果我们需要处理这个错误，那么我么可以使用 do-catch进行捕获

```swift
    func howToTryCatch() {
        do {
            let textData = "1111".data(using: .utf8)
            try textData?.write(to: URL(string: "")) 
        } catch {
            print(error.localizedDescription)
        }
    }
```
这样我们就可以处理这个方法调用时可能出现的错误了


### 如何写一个可以抛出异常的方法

假设，我们写的某个方法可能需要抛出异常，那么我们应该如何写呢？

```swift
    func throwsErrorFuction(path: String?) throws -> String {
        guard let notNilPath = path else {
            throw NSError(domain: "1", code: 100001)
        }
        return "success \(notNilPath)"
    }
```
- 要抛出异常的方法需要使用throws进行修饰
- 需要抛出异常的位置使用throw 进行抛出异常，抛出的异常可以是遵守ErrorType协议的错误

### 异常的传递

当我们调用一个可能会throw异常的方法时，如果我们不通过do-catch进行捕获，那么会出现什么问题呢？

![](https://tva1.sinaimg.cn/large/008vxvgGgy1h7cx2of2sbj31n004caal.jpg)

通过上图我们发现，在调用可能会throw异常的方法时，我们必须使用 do-Catch进行异常捕获(这里如果使用try? 则不需要)。

但是 如果某些场景下，我们不希望在此处去处理异常，而是希望他向上传递呢？

```swift
    func test() throws {
        let result = try throwsErrorFuction(path: "1")
        print(result)
    }
```

我们可以通过这个方法将异常上抛

```swift
    func doTest() {
        do {
            try test()
        } catch {
            print(error.localizedDescription)
        }
    }
```

![](https://tva1.sinaimg.cn/large/008vxvgGgy1h7cxdnshkyj31g80s2n19.jpg)

但是，不建议错误层层上抛的方式，因为上层调用时并不想关注底层可能出现的所有问题，有些错误尽量可以在内部处理。



### 参考文献
[如何在 Swift 中进行错误处理](https://swift.gg/2016/06/12/let-it-throw/)